### ISSUE TITLE
i cant connect in agar.io client

### ISSUE THREAD

**Issue by Jahseeh** [Luka967/OgarII#23]
i tried to use core.connect but doesnt work, also y try FirstCodeReviewer extencion and nothing!

**Comment by freaky767** [comment]
multiogar is pretty dead and hasnt been updated in a while lul

**Comment by Jahseeh** [comment]
OgarII doesnt work in agar.io client too :(

**Comment by SuperOP535** [comment]
@chewyiscrunchy Are you blind? It gets updates frequently

**Comment by freaky767** [comment]
it does get updated quite frequently as luka is adding and fixing stuff constantly.

**Comment by Jahseeh** [comment]
protocol problem

**Comment by freaky767** [comment]
The new version fixes this, close issue.
