### ISSUE TITLE
cannot connect using original agario client

### ISSUE THREAD

**Issue by freaky767** [Luka967/OgarII#24]
i have disabled Integrity checks and then tried connecting to the server, but it spews out an error
![image](https://user-images.githubusercontent.com/23425837/43688455-2a486f32-98e1-11e8-8caf-d4a895b00719.png)

**Comment by freaky767** [comment]
that is windows powershell, thats why its blue

**Comment by DeadLord1337** [comment]
agario client work 1.1.6
