### ISSUE TITLE
chat error

### ISSUE THREAD

**Issue by Niall7459** [Luka967/OgarII#26]
so you don't forget...

Chat fails.

Tested protocol: 5
How to reproduce: chat
Outcome: No chat is displayed on the chat board.
Expected Outcome: Chat to be displayed on chat board.

**Comment by Niall7459** [comment]
Update: this was a client problem, however OgarII is cutting the last character in chat messages.

**Comment by SuperOP535** [comment]
warning: unsure; It's likely that you forgot to add a null character so it strips the last char instead of the null

**Comment by Niall7459** [comment]
Why should their be a null character?

**Comment by SuperOP535** [comment]
because that's how strings in buffers work, you terminate it with a null char, try adding one and see what happens.

**Comment by Niall7459** [comment]
Yeah protocol 5 didn’t h
