### ISSUE TITLE
License is unfriendly

### ISSUE THREAD

**Issue by B0RYS** [Luka967/OgarII#39]
Can you please use nicer words please

**Comment by chewyiscrunchy** [comment]
shut up poopoo nigga

**Comment by B0RYS** [comment]
don't say such words. the p word is prohibited.

**Comment by chewyiscrunchy** [comment]
sorry i meant peepee

**Comment by Luka967** [comment]
heck

**Comment by B0RYS** [comment]
okay this isn't it gamers.

**Comment by B0RYS** [comment]
words of such weight are punishable by several lifetimes in hell.

**Comment by B0RYS** [comment]
pray to jeuse to clean your soul of sins
![](https://i.redd.it/809ha9x32xq01.jpg)

**Comment by Luka967** [comment]
seriously though, this isn't funny

**Comment by B0RYS** [comment]
sErIoUsLy ThOuGh, ThIs iSn'T fUnNy

**Comment by chewyiscrunchy** [comment]
lua your repository issues are basically reddit

**Comment by B0RYS** [comment]
i agree

**Comment by B0RYS** [comment]
but in realtime

**Comment by Luka967** [comment]
github for this community
is reddit
