### ISSUE TITLE
Chat Issue 2

### ISSUE THREAD

**Issue by fmrmx** [Luka967/OgarII#43]
Version: OgarII 1.2.2

Steps to reproduce.
1. run OgarII v1.2.2 with node index.js
2. Install fresh copy of Cigar2 (Protocol 6) or Luka's Cigar (Protocol 6)
3. Write in chat.

Issue: no colors shown on chat.

**Comment by Niall7459** [comment]
Can confirm on Cigar (5) as well.

**Comment by Niall7459** [comment]
In World.js at Line 240  Put `player.chatColor = color;`

**Comment by Luka967** [comment]
Resolved in 1.3.0
