### ISSUE TITLE
Numerous issues need to be addressed.

### ISSUE THREAD

**Issue by Niall7459** [Luka967/OgarII#44]
Chat Name Colour Issue: https://github.com/Luka967/OgarII/issues/43, When the player "enters" the game they remain with the grey spectator color.

Event/Extension API: https://github.com/Luka967/OgarII/issues/17. Add an event system. Event just a basic abstract Listener class.

Regards

**Comment by Borys-K** [comment]
![Eatmypenis](https://user-images.githubusercontent.com/36678225/58368874-c5f31500-7eea-11e9-9beb-05396cdb319c.png)

**Comment by Luka967** [comment]
Chat name color issue has been resolved. Closing this issue in favor of #17
