### ISSUE TITLE
Numerous issues need to be addressed.

### ISSUE THREAD

**Issue by BorysDev** [Luka967/OgarII#45]
Chat Name Colour Issue: #43, When the player "enters" the game they remain with the grey spectator color.

Event/Extension API: #17. Add an event system. Event just a basic abstract Listener class.

Regards

**Comment by Niall7459** [comment]
Mug

**Comment by BorysDev** [comment]
been over a week

**Comment by Luka967** [comment]
Chat name color issue has been resolved. Closing this issue in favor of #17
