### ISSUE TITLE
What is better?

### ISSUE THREAD

**Issue by TopoR1** [Luka967/OgarII#47]
How is OgarII better than MultiOgar?

**Comment by AlexHGaming** [comment]
This issue is solved by playing on both projects then decide for yourself.

**Comment by Luka967** [comment]
Comparing them would be like comparing apples to oranges.
However in short; MultiOgar, MultiOgar-Edited and OgarII all work. Where they differ is:
- MultiOgar was made just to be working
- MultiOgar-Edited is mostly intended for fun, having a lot of features
- OgarII was made for a production setting, where you'd want something that'll stay up for a long time, nothing that isn't going to be used, and is easily modifiable

Any other questions regarding this should go in this Discord, as this is misuse of GitHub issues:
https://discord.gg/XcKgShT
