### ISSUE TITLE
do someone tried to fix teams mode new update?

### ISSUE THREAD

**Issue by ThebigbossCE** [Luka967/OgarII#48]
idk if u tried, but, with the new agario teams mode update the teams mode leaderboard colors are broken

anyone have already tried to fix it ?

**Comment by Luka967** [comment]
Thank you for bringing it up. The netcode regarding pie leaderboards got changed. Next patch version should address this.

**Comment by Luka967** [comment]
1.3.3 has been released to address this issue

**Comment by ThebigbossCE** [comment]
okay thank you for your answer
