### ISSUE TITLE
The run file is missing :/

### ISSUE THREAD

**Issue by lbougot** [Luka967/OgarII#49]
Please is it still possible to run this? And how?

**Comment by Luka967** [comment]
Literally README:

> 1. Make sure you have node.js version 8 or greater.
> 2. Make sure you have a C++11 compliant compiler for building uWebSockets.
>     - If you're on Windows, `npm install -g windows-build-tools`.
>     - If you're on GNU/Linux, use your package manager to install a supported C++ compiler such as GCC.
> 3. Clone / [download](https://github.com/Luka967/OgarII/archive/master.zip) the repo.
> 4. `npm install` in `/`.
> 5. `cd ./cli/`
> 6. `node index.js`
