### ISSUE TITLE
Same error

### ISSUE THREAD

**Issue by freaky767** [Luka967/OgarII#5]
The server still doesn't start, gives the same error as before.

**Comment by DeadLord1337** [comment]
@freaky767 What error, screenshot plz

**Comment by Luka967** [comment]
I forgot to ask what version of node are you using. I've used a ton of ES6 features that are not available in older node versions. Try updating to the current LTS one.

**Comment by SuperOP535** [comment]
es6 ftw

**Comment by freaky767** [comment]
okay, ill try.

**Comment by freaky767** [comment]
okay yeah i was running an old version of nodejs
