### ISSUE TITLE
ERTP controls and Q control key don't work on the original agar.io client.

### ISSUE THREAD

**Issue by kalinitta** [Luka967/OgarII#57]
Basically I can't control minions despite I've disabled my macro script (it doesn't work too tho).
What can I do to solve this problem?
Thanks in advance.

**Comment by kalinitta** [comment]
Ok so i solved this problem on my own with a script, closing.

**Comment by Teii1** [comment]
how?

**Comment by kalinitta** [comment]
> how?

i just yoinked a script from another agar server repo and adjusted it to my liking. I don't remember which one, it's been a long time.
