### ISSUE TITLE
Freeze keybind (Help needed)

### ISSUE THREAD

**Issue by Phoenix132** [Luka967/OgarII#61]
Recently I opened an OgarII project on glitch.com and I want to create a freeze keybind. So it sets the collide delay to 100 and moveMult to 0. Any ideas/suggestions?

**Comment by Phoenix132** [comment]
Lol, no one?

**Comment by TopoR1** [comment]
Either this is nonsense, or I did not understand the idea.

**Comment by Phoenix132** [comment]
huh

**Comment by Phoenix132** [comment]
ok so basically i want a freeze keybind that disables your movement and collision of cells

**Comment by Phoenix132** [comment]
Soo the code is here on glitch.com/edit/#!/ogartest   and you need a cigar client to see the results which is on usa-agar.glitch.me

**Comment by Phoenix132** [comment]
:/ no help yet

**Comment by Phoenix132** [comment]
No one is helping me so imma close it
